name: test

on: [push]
  
jobs:
  Test-all:
    runs-on: ubuntu-latest
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup nextflow
        run: curl -s https://get.nextflow.io | bash && cp nextflow /usr/local/bin
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - uses: actions/checkout@v3
      - name: Test demux pipeline
        working-directory: ./metaflowmics
        run: make testdemux
      - name: Test 16S pipeline
        working-directory: ./metaflowmics
        run: make test16S
      - name: Test ITS pipeline
        working-directory: ./metaflowmics
        run: make testITS
      - name: Test COI pipeline
        working-directory: ./metaflowmics
        run: make testCOI

