name: test

on:
  push:
    paths:
      - '**.nf'
      - '**.config'

jobs:
  Test-all:
    runs-on: ubuntu-latest
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup nextflow
        run: curl -s https://get.nextflow.io | bash && cp nextflow /usr/local/bin
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Pull repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Test COI pipeline
        working-directory: ./metaflowmics
        run: nextflow run Pipeline-COI -profile local,docker,testCOI
      - name: Test ITS pipeline
        working-directory: ./metaflowmics
        run: nextflow run Pipeline-ITS -profile local,docker,testITS --skip_lulu
      - name: Test demux pipeline
        working-directory: ./metaflowmics
        run:  nextflow run multithreaded-demux -profile local,docker,testDemux
      - name: Test 16S pipeline
        working-directory: ./metaflowmics
        run: nextflow run Pipeline-16S -profile local,docker,test16S --skip_lulu

